### PR TITLE
add explicit version check for setuptools

### PR DESCRIPTION
**Pull request by pianoman19372**
sprockets-postgres does not install properly with older versions of setuptools.

this adds a check to alert the developer of the issue

### CODE REVIEW

**Comment by gmr** [comment]
IIRC there's a way to do this in `setup.cfg` instead of `setup.py`, and I'd rather go that route. I'll find docs on it and shoot it your way.

**Comment by gmr** [comment]
I believe you can do the following to achieve the same result without modifying `setup.py`, though I've not tried pinning in that directive.

```
[metadata]
...
requires-dist = setuptools>=40.6
```
Per example in https://github.com/embray/setup.cfg/blob/master/README.rst

**Comment by gmr** [comment]
Or create a pyproject.toml with:

[build-system]
requires = [
  "setuptools >= 40.6.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

**Comment by dave-shawley** [comment]
@gmr you are better off using `pkg_resources.requires` in the setup.py to catch the versions of setuptools that did not read metadata from setup.cfg at all (e.g., older than [v30.3.0 Dec 2018](https://setuptools.readthedocs.io/en/latest/history.html#v30-3-0)).  Though I think that you get a really obtuse failure in that case since `setuptools.setup` doesn't like being called without arguments IIRC.

**Pull request merged**
